### PR TITLE
Added JSON schema support to CI

### PR DESCRIPTION
**Pull request by scribblemaniac**
Also fixed a few of this issues that showed up as a result. I have no experience with CircleCI, but it seems logical that this should work. Country codes

json-spec is not particularly verbose, so I would recommend putting the schema.json and data.json files into [JSON Schema Lint](http://jsonschemalint.com/draft4/). It shows a snippet from the section where the error occurs which makes things a lot easier to debug than giving the array index.

This may have to be tweaked depending on what is done at #275.

### CODE REVIEW

**Comment by dkhamsing** [comment]
Hey can u send your changes to https://github.com/dkhamsing/open-source-ios-apps/tree/structure

**Comment by scribblemaniac** [comment]
Sure, give me a sec

**Comment by dkhamsing** [comment]
Wow this validate is cool

**Comment by scribblemaniac** [comment]
This is my first time working with JSON Schema and I have to agree, it's pretty cool!

**Pull request closed without merging**
