### PR TITLE
added awesome swift iOS app

### PR DESCRIPTION
**Pull request by matteocrippa**
Added awesome swift app source

### CODE REVIEW

**Comment by scribblemaniac** [comment]
So Awesome Swift gets an app before we do 😒 

You're missing a comma on the description line, which is causing all of our tests to freak out. Additionally MIT should be lowercase to follow our conventions.

**Comment by matteocrippa** [comment]
@scribblemaniac it should be fixed, for the app feel free to use the awesome swift one, you know we're using the same approach to generate the md file via json

**Comment by scribblemaniac** [comment]
It might be nice to have support adding different JSON urls within the app. Unfortunately I do not know Swift well enough to make that change myself.

**Comment by matteocrippa** [comment]
@scribblemaniac you mean adding a switcher at the early page where the user can switch within different awesome repositories based on json version?

**Comment by scribblemaniac** [comment]
Yeah exactly, or some similar option menu in a toolbar.

**Comment by matteocrippa** [comment]
Mhhh dunno if placing there or a menu slider from the right... Suggestions are welcome

**Pull request merged**
