### PR TITLE
Move screenshots below the license

### PR DESCRIPTION
**Pull request by vpeschenkov**
## FROM
Alt text
## TO
Alt text

### CODE REVIEW

**Comment by dkhamsing** [comment]
This looks good but clicking or tapping on the number link is not improved.. thoughts ?

**Comment by vpeschenkov** [comment]
Good catch... I forgot about mobile devices. On desktops, it is very simple to open links with "Ctrl" :-). In this case, I can just move the line with links down, just after License. Do you agree?

**Comment by vpeschenkov** [comment]
BTW, I've been thinking about removing the source link and move the one to the title. Something like this:

[Artsy Shows](https://github.com/artsy/Emergence) - Art shows

It seems like an easier way to navigate through apps. We don't need to open details to navigate to sources. What is your opinion?

**Comment by vpeschenkov** [comment]
@dkhamsing Updated to this:
Alt text

Link to an entire [REAME.md](https://github.com/vpeschenkov/open-source-ios-apps)

If this one is good, we can merge it. I'll make another PR for titles when I get time.

**Comment by dkhamsing** [comment]
Thank you @vpeschenkov !

**Pull request merged**
