### PR TITLE
[script] Update header

### LINKED ISSUE #933: Truncated README
It appears GitHub now clips/trims the README when you visit the repo: https://github.com/dkhamsing/open-source-ios-apps

### PR DESCRIPTION
**Pull request by vpeschenkov**
@dkhamsing see the result [here](https://github.com/vpeschenkov/open-source-ios-apps/tree/issues/GI-933). Is it fine?

Close #933

### CODE REVIEW

**Comment by dkhamsing** [comment]
Hm I was thinking of only changing the header, this is different. Interesting though, thank you

Will think on it

**Comment by vpeschenkov** [comment]
That's fine 🙂  I see it this way because changing only the header won't fix the issue with truncating completely (while this way fixes it completely). I only have some concerns about how it will affect on search engines like Google and others, but I have no answer anyway... So, the decision is up to you 🙂

**Comment by dkhamsing** [comment]
Went a different way #935
Thanks

**Comment by vpeschenkov** [comment]
Nice it was fixed this way. Good job 👍

**Pull request closed without merging**
