### PR TITLE
Add MiamiSunglasses by @DeveloperACE

### PR DESCRIPTION
**Pull request by DeveloperACE**
0. [x] Project URL: none
1. [x] Update contents.json instead of README 
2. [x] One project per pull request
3. [x] Project added at the end of the list (a script sorts projects automatically)
4. [x] Avoid iOS or open-source in description as it is assumed
5. [x] Use this commit title format if applicable: Add app-name by @github-username
6. [x] Use approved format for your entry

### CODE REVIEW

**Comment by DeveloperACE** [comment]
WHAT did i do THIS time?

**Comment by dkhamsing** [comment]
Hah let me see

**Comment by dkhamsing** [comment]
Ah you're fine, just something on our end

Thank you!

**Comment by DeveloperACE** [comment]
what is the 'checks' thing that has to run to merge the branch?

**Comment by dkhamsing** [comment]
Just some validation we do, it's different for each project

For us, we check that the json data is "good" and also that the links in the whole project are still good

**Comment by dkhamsing** [comment]
Oh if you're talking about the GitHub side, it's to see if your changes can be incorporated automatically.. see if someone updates the same area of the file as you, then there is a conflict

**Pull request merged**
