### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Skornos**
1. [ ] Project URL:
2. [ ] One project per pull request
3. [ ] Project added at the end of the list (a script sorts projects automatically)
4. [ ] Avoid iOS or open-source in description as it is assumed
5. [ ] Use this commit title format if applicable: Add app-name by @github-username
6. [ ] Use approved format for your entry

We got 100 stars! :D

### CODE REVIEW

**Comment by dkhamsing** [comment]
Hey thanks for the update
However to make a change, you have to update contents.json instead of the readme

**Comment by DeveloperACE** [comment]
@dkhamsing you should make that clear in the readme...

**Comment by dkhamsing** [comment]
Yeah it's in a lot of places actually including the readme when you edit it

**Comment by dkhamsing** [comment]
@Skornos actually we now have a script to update stars (about once a month) so this will get resolved by itself later 😄

**Comment by Skornos** [comment]
awesome, thanks 👍

**Comment by dkhamsing** [comment]
@Skornos  https://github.com/dkhamsing/open-source-ios-apps/commit/6b2bcefb7244df185a491dfd14fb07fae5d84d75#diff-04c6e90faac2675aa89e2176d2eec7d8L750

**Pull request closed without merging**
