### PR TITLE
Add Pastebin Mobile by @Aecasorg

### PR DESCRIPTION
**Pull request by Aecasorg**
1. [✓] Project URL: https://github.com/jonluca/PasteBinApp
2. [✓] Update contents.json instead of README 
3. [✓] One project per pull request
4. [✓] Avoid iOS or open-source in description as it is assumed
5. [✓] Use this commit title format if applicable: Add app-name by @github-username
6. [✓] Use approved format for your entry

### CODE REVIEW

**Comment by Aecasorg** [comment]
Uhm, links that I have no control over, what do I do?

**Comment by vpeschenkov** [comment]
@Aecasorg Hi! Don't worry about them, we'll fix the ones later.

**Comment by Aecasorg** [comment]
@vpeschenkov OK, great thanks!

**Comment by vpeschenkov** [comment]
@Aecasorg Thank you for the contribution!

**Comment by Aecasorg** [comment]
Thanks!

**Pull request merged**
