### PR TITLE
Add SHMUP by @fabiensanglard

### PR DESCRIPTION
**Pull request by Wofiel**
Adds SHMUP - http://fabiensanglard.net/shmup/

A multiplatform engine primarily written in ANSI C with wrappers for platform specific code, including, of course, iOS.

### CODE REVIEW

**Comment by dkhamsing** [comment]
can you rebase/fix the conflicts?

**Comment by Wofiel** [comment]
Also fixed the formatting of Swab using tabs instead of spaces on the braces.

**Comment by dkhamsing** [comment]
thx!

**Comment by dkhamsing** [comment]
@Wofiel do you know if the license is any of the following?

"gpl-3.0", "lgpl-3.0",  "lgpl-2.1", "gpl-2.0", "agpl-3.0"

**Comment by Wofiel** [comment]
Listed in the source as GPLv3, my apologies for not being specific before merge.

**Comment by dkhamsing** [comment]
np, thx

**Pull request merged**
