### PR TITLE
Fix links

### PR DESCRIPTION
**Pull request by vpeschenkov**
It seems like the sources were removed.

### CODE REVIEW

**Comment by dkhamsing** [comment]
If that is the case, we should archive the apps - not delete the entries.

**Comment by vpeschenkov** [comment]
> We should archive the apps, not delete the entries

But if there is no source code?

**Comment by dkhamsing** [comment]
@vpeschenkov I was thinking the important thing is to maintain the active list. Archiving is fine in this case as well. Let me know what you think 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vpeschenkov** [comment]
> @vpeschenkov I was thinking the important thing is to maintain the active list. Archiving is fine in this case as well. Let me know what you think

@dkhamsing  Finally, I understood the meaning :-)

1. In this case, I think we have to remove all the links from the `ARCHIVE.md` list. Because that list has links that lead to source code, but there is no source code anymore :-). I see `ARCHIVE.md` as a place for old/unsupported projects, but with source code.

2. I don't understand for which reason we need to keep such kind of projects? If we keep projects without code, there is no sense. Such kind of projects doesn't make a value for a user because the most value is source code (I don't see any value in keeping a project name + description :-)).

So, if there is no source code, I think we have to remove such items from the list completely.

**Comment by dkhamsing** [comment]
Hmm good point. The user @opensourceios usually archives code but if u can confirm it is missing there too, let’s delete 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request closed without merging**
