### PR TITLE
Update categories

### LINKED ISSUE #411: Categories
@scribblemaniac 

1. I'm thinking of changing `category` so that all the values are lists
- Should it be renamed to `category-ids`

More consistent
Let me know what you think

### PR DESCRIPTION
**Pull request by dkhamsing**
`category` is now `category-ids`, always a list

Close #411

@scribblemaniac

### CODE REVIEW

**Comment by dkhamsing** [comment]
cc @matteocrippa

**Comment by matteocrippa** [comment]
we should have to upgrade this also in awesome-swift and then in the iOS app, am I correct?

**Comment by dkhamsing** [comment]
@matteocrippa definitely in the ios app, can we leave awesome-swift as is?

**Comment by matteocrippa** [comment]
@dkhamsing prob it would useful to have the same value in both for mapping, but It would break the actual app

**Comment by dkhamsing** [comment]
I know it's not great.. but for now can we have two mappings for `category` in the app?

**Pull request merged**
