### PR TITLE
Fix extra empty lines in Developer, Browser sections

### LINKED ISSUE #666: Extra empty lines in Developer, Browser sections
Must be something in th convert script 😅

### PR DESCRIPTION
**Pull request by vpeschenkov**
Close #666

### CODE REVIEW

**Comment by vpeschenkov** [comment]
## News 
 
[back to top](#readme) 
 
- Designer News: Browse the https://www.designernews.co/ design & technology site  
  <details><summary><code>swift</code> ⭐⭐⭐⭐⭐</summary>

  https://github.com/MengTo/DesignerNewsApp<br>  Added March 15, 2015<br>  License: `other`
 <br><a href='https://cdn-images-1.medium.com/max/800/1*NeMFTvgJVJiM8aiy4Pambw.png'><code>Screenshot 1</code></a> 
  </details>

- GrinnellEvents: Grinnell College campus events  
  <details><summary><code>objc</code> </summary>

  https://github.com/kvnbautista/Grinnell-Events-iOS<br>  Added October 16, 2015<br>  License: [`gpl-2.0`](http://choosealicense.com/licenses/gpl-2.0/)
 <br><a href='http://a3.mzstatic.com/us/r30/Purple1/v4/6e/46/d1/6e46d11f-87e0-0015-cc26-d19bf960a9a9/screen696x696.jpeg'><code>Screenshot 1</code></a> <a href='http://a4.mzstatic.com/us/r30/Purple5/v4/e0/29/8c/e0298c8d-bbea-170f-83b8-6939787fc024/screen696x696.jpeg'><code>Screenshot 2</code></a> <a href='http://a5.mzstatic.com/us/r30/Purple3/v4/db/93/8a/db938a1c-e143-546b-c453-3b0864599163/screen696x696.jpeg'><code>Screenshot 3</code></a> 
  </details>

- Keinex tech blog  
  <details><summary><code>swift</code> </summary>

  https://github.com/Keinex/Keinex-iOS<br>  Added August  8, 2016<br>  License: [`mit`](http://choosealicense.com/licenses/mit/)
 <br><a href='https://github.com/Keinex/Keinex-iOS/blob/master/1.jpg'><code>Screenshot 1</code></a> <a href='https://github.com/Keinex/Keinex-iOS/blob/master/2.jpg'><code>Screenshot 2</code></a> 
  </details>

- LobsterApp: Browse the https://lobste.rs community news site  
  <details><summary><code>objc</code> </summary>

  https://github.com/rhysforyou/LobsterApp<br>  Added July 21, 2016<br>  License: `other`
 <br><a href='https://i.imgur.com/WF6eY71.png'><code>Screenshot 1</code></a> 
  </details>

- lobsters-reader  
  <details><summary><code>swift</code> </summary>

  https://github.com/cfdrake/lobsters-reader<br>  Added June 13, 2017<br>  License: [`mit`](http://choosealicense.com/licenses/mit/)
 <br><a href='https://raw.githubusercontent.com/cfdrake/lobsters-reader/master/Assets/screenshot.png'><code>Screenshot 1</code></a> 
  </details>

- NirZhihuDaily2.0  
  <details><summary><code>objc</code> 🌐 ⭐⭐⭐⭐</summary>

  https://github.com/zpz1237/NirZhihuDaily2.0<br>  Added November  4, 2015<br>  License: [`mit`](http://choosealicense.com/licenses/mit/)
 <br><a href='https://github.com/zpz1237/NirZhihuDaily2.0/raw/master/effect1.gif'><code>Screenshot 1</code></a> 
  </details>

- TabDump: TabDump news app  
  <details><summary><code>afnetworking</code> </summary>

  https://github.com/dkhamsing/TabDump<br>  Added January 26, 2015<br>  License: [`mit`](http://choosealicense.com/licenses/mit/)
 <br><a href='https://github.com/dkhamsing/TabDump/raw/master/assets/screenshots/screenshot.png'><code>Screenshot 1</code></a> 
  </details>

- The Oakland Post: Oakland University student-run newspaper in Rochester, Michigan  
  <details><summary><code>swift</code> ⭐⭐</summary>

  https://github.com/aclissold/the-oakland-post<br>  Added March 18, 2015<br>  License: [`bsd-3-clause`](http://choosealicense.com/licenses/bsd-3-clause/)  </details>

- v2ex: Browse the https://www.v2ex.com/ startup, designer & developer site [` App Store`](https://itunes.apple.com/app/v2ex-chuang-yi-gong-zuo-zhe/id898181535)  
  <details><summary><code>objc</code> 🌐 ⭐⭐⭐⭐</summary>

  https://github.com/singro/v2ex<br>  Added April 19, 2015<br>  License: [`mit`](http://choosealicense.com/licenses/mit/)
 <br><a href='http://a4.mzstatic.com/us/r30/Purple18/v4/cd/7e/af/cd7eafe2-9672-c37a-9c95-bad1651e23b9/screen696x696.jpeg'><code>Screenshot 1</code></a> <a href='http://a1.mzstatic.com/us/r30/Purple18/v4/d5/a3/18/d5a31896-d70d-9d06-ba50-004df03d3735/screen696x696.jpeg'><code>Screenshot 2</code></a> <a href='http://a2.mzstatic.com/us/r30/Purple20/v4/af/75/88/af7588a9-8481-5d75-f3fd-8b1aa0a35bd6/screen696x696.jpeg'><code>Screenshot 3</code></a> <a href='http://a5.mzstatic.com/us/r30/Purple60/v4/3a/cb/a3/3acba32e-10c3-4916-1136-ebb922c33a2a/screen696x696.jpeg'><code>Screenshot 4</code></a> <a href='http://a4.mzstatic.com/us/r30/Purple30/v4/ac/80/bb/ac80bbc1-1f81-1faf-26a0-c141e515082c/screen696x696.jpeg'><code>Screenshot 5</code></a> 
  </details>

- ZeitSuche: Search for articles published by Germany's 'Zeit' newspaper.  
  <details><summary><code>swift</code> <code>iphone</code> </summary>

  https://github.com/niftycode/ZeitSuche_iOS<br>  Added June  7, 2017<br>  License: [`mit`](http://choosealicense.com/licenses/mit/)
 <br><a href='https://bodo-schoenfeld.de/wp-content/uploads/2016/07/ZeitSuche-Screenshot.png'><code>Screenshot 1</code></a> 
  </details>

----

**Comment by vpeschenkov** [comment]
@dkhamsing Honestly, I don't know Ruby, if something can be done by another way, don't hesitate to say that.

**Comment by vpeschenkov** [comment]
## News 
 
[back to top](#readme) 
 
- Designer News: Browse the https://www.designernews.co/ design & technology site  
  <details><summary><code>swift</code> ⭐⭐⭐⭐⭐</summary>

  https://github.com/MengTo/DesignerNewsApp<br>  Added March 15, 2015<br>  License: `other`
<a href='https://cdn-images-1.medium.com/max/800/1*NeMFTvgJVJiM8aiy4Pambw.png'><code>Screenshot 1</code></a> <br>
  </details>

- GrinnellEvents: Grinnell College campus events  
  <details><summary><code>objc</code> </summary>

  https://github.com/kvnbautista/Grinnell-Events-iOS<br>  Added October 16, 2015<br>  License: [`gpl-2.0`](http://choosealicense.com/licenses/gpl-2.0/)
<a href='http://a3.mzstatic.com/us/r30/Purple1/v4/6e/46/d1/6e46d11f-87e0-0015-cc26-d19bf960a9a9/screen696x696.jpeg'><code>Screenshot 1</code></a> <a href='http://a4.mzstatic.com/us/r30/Purple5/v4/e0/29/8c/e0298c8d-bbea-170f-83b8-6939787fc024/screen696x696.jpeg'><code>Screenshot 2</code></a> <a href='http://a5.mzstatic.com/us/r30/Purple3/v4/db/93/8a/db938a1c-e143-546b-c453-3b0864599163/screen696x696.jpeg'><code>Screenshot 3</code></a> <br>
  </details>

- Keinex tech blog  
  <details><summary><code>swift</code> </summary>

  https://github.com/Keinex/Keinex-iOS<br>  Added August  8, 2016<br>  License: [`mit`](http://choosealicense.com/licenses/mit/)
<a href='https://github.com/Keinex/Keinex-iOS/blob/master/1.jpg'><code>Screenshot 1</code></a> <a href='https://github.com/Keinex/Keinex-iOS/blob/master/2.jpg'><code>Screenshot 2</code></a> <br>
  </details>

- LobsterApp: Browse the https://lobste.rs community news site  
  <details><summary><code>objc</code> </summary>

  https://github.com/rhysforyou/LobsterApp<br>  Added July 21, 2016<br>  License: `other`
<a href='https://i.imgur.com/WF6eY71.png'><code>Screenshot 1</code></a> <br>
  </details>

- lobsters-reader  
  <details><summary><code>swift</code> </summary>

  https://github.com/cfdrake/lobsters-reader<br>  Added June 13, 2017<br>  License: [`mit`](http://choosealicense.com/licenses/mit/)
<a href='https://raw.githubusercontent.com/cfdrake/lobsters-reader/master/Assets/screenshot.png'><code>Screenshot 1</code></a> <br>
  </details>

- NirZhihuDaily2.0  
  <details><summary><code>objc</code> 🌐 ⭐⭐⭐⭐</summary>

  https://github.com/zpz1237/NirZhihuDaily2.0<br>  Added November  4, 2015<br>  License: [`mit`](http://choosealicense.com/licenses/mit/)
<a href='https://github.com/zpz1237/NirZhihuDaily2.0/raw/master/effect1.gif'><code>Screenshot 1</code></a> <br>
  </details>

- TabDump: TabDump news app  
  <details><summary><code>afnetworking</code> </summary>

  https://github.com/dkhamsing/TabDump<br>  Added January 26, 2015<br>  License: [`mit`](http://choosealicense.com/licenses/mit/)
<a href='https://github.com/dkhamsing/TabDump/raw/master/assets/screenshots/screenshot.png'><code>Screenshot 1</code></a> <br>
  </details>

- The Oakland Post: Oakland University student-run newspaper in Rochester, Michigan  
  <details><summary><code>swift</code> ⭐⭐</summary>

  https://github.com/aclissold/the-oakland-post<br>  Added March 18, 2015<br>  License: [`bsd-3-clause`](http://choosealicense.com/licenses/bsd-3-clause/)<br>
  </details>

- v2ex: Browse the https://www.v2ex.com/ startup, designer & developer site [` App Store`](https://itunes.apple.com/app/v2ex-chuang-yi-gong-zuo-zhe/id898181535)  
  <details><summary><code>objc</code> 🌐 ⭐⭐⭐⭐</summary>

  https://github.com/singro/v2ex<br>  Added April 19, 2015<br>  License: [`mit`](http://choosealicense.com/licenses/mit/)
<a href='http://a4.mzstatic.com/us/r30/Purple18/v4/cd/7e/af/cd7eafe2-9672-c37a-9c95-bad1651e23b9/screen696x696.jpeg'><code>Screenshot 1</code></a> <a href='http://a1.mzstatic.com/us/r30/Purple18/v4/d5/a3/18/d5a31896-d70d-9d06-ba50-004df03d3735/screen696x696.jpeg'><code>Screenshot 2</code></a> <a href='http://a2.mzstatic.com/us/r30/Purple20/v4/af/75/88/af7588a9-8481-5d75-f3fd-8b1aa0a35bd6/screen696x696.jpeg'><code>Screenshot 3</code></a> <a href='http://a5.mzstatic.com/us/r30/Purple60/v4/3a/cb/a3/3acba32e-10c3-4916-1136-ebb922c33a2a/screen696x696.jpeg'><code>Screenshot 4</code></a> <a href='http://a4.mzstatic.com/us/r30/Purple30/v4/ac/80/bb/ac80bbc1-1f81-1faf-26a0-c141e515082c/screen696x696.jpeg'><code>Screenshot 5</code></a> <br>
  </details>

- ZeitSuche: Search for articles published by Germany's 'Zeit' newspaper.  
  <details><summary><code>swift</code> <code>iphone</code> </summary>

  https://github.com/niftycode/ZeitSuche_iOS<br>  Added June  7, 2017<br>  License: [`mit`](http://choosealicense.com/licenses/mit/)
<a href='https://bodo-schoenfeld.de/wp-content/uploads/2016/07/ZeitSuche-Screenshot.png'><code>Screenshot 1</code></a> <br>
  </details>

**Comment by vpeschenkov** [comment]
Looks weird, if I use this code everything seems to be fine:
```
    details << "<br>"
    details << "</details>\n\n"
```
but if I use this code:
```
    details << "<br>"
    details << "\n </details>\n\n"
```
It adds extra space for the details view like "\n" is a content. That is why I can't keep that new line for`details` view.

**Comment by dkhamsing** [comment]
Thx for the pr, apologies it will take me some time before I can review.

**Pull request merged**
