### PR TITLE
Added IDResistors.

### PR DESCRIPTION
**Pull request by thestoneage**
1. [x] Project URL:
2. [x] Update contents.json instead of README 
3. [x] One project per pull request
4. [x] Screenshot included 
5. [x] Avoid iOS or open-source in description as it is assumed
6. [x] Use this commit title format if applicable: Add app-name by @github-username
7. [ ] Use approved format for your entry

### CODE REVIEW

**Comment by thestoneage** [comment]
Added my own SwiftUI Project.

**Comment by dkhamsing** [comment]
@thestoneage cool - did you mean to close the pull request?

**Comment by thestoneage** [comment]
No I didn't, sorry for the inconvenience.

**Comment by dkhamsing** [comment]
Hm I'm unable to reopen the pull request. It's ok, will add this separately- thx

**Pull request closed without merging**
