### PR TITLE
Added MiamiSunglasses by @DeveloperACE

### PR DESCRIPTION
**Pull request by DeveloperACE**
0. [x] Project URL: none. My personal website is www.adriancedwards.com
1. [x] Update contents.json instead of README 
2. [x] One project per pull request
3. [x] Project added at the end of the list (a script sorts projects automatically)
4. [x] Avoid iOS or open-source in description as it is assumed
5. [x] Use this commit title format if applicable: Add app-name by @github-username
6. [x] Use approved format for your entry

### CODE REVIEW

**Comment by DeveloperACE** [comment]
Is it a good idea to delete my fork of your repo once the pull request has been accepted?

**Comment by kvnbautista** [comment]
@DeveloperACE  it doesn't matter tbh

**Comment by DeveloperACE** [comment]
Ok

**Comment by dkhamsing** [comment]
Deleting your fork only matters before it is merged (then you can update the pull request).. after it is merged, it should be deleted just for housekeeping (it does not affect the repo you are contributing to)

**Comment by dkhamsing** [comment]
@DeveloperACE can you fix the conflicts? If not I can help you do it

**Comment by DeveloperACE** [comment]
Ok

**Comment by DeveloperACE** [comment]
Umm... Im kinda new to github, how do I go about doing this? Shall I refork the repo and submit a new pull request?

**Comment by dkhamsing** [comment]
Doing this through the GitHub interface is a little harder but it can be done

Hold on

**Comment by DeveloperACE** [comment]
So I would need to use hit on the command line?

_____________________________
Adrian Edwards

www.adriancedwards.com



_____________________________
Adrian Edwards

www.adriancedwards.com

**Comment by dkhamsing** [comment]
@DeveloperACE no no, it's ok

In short, go to https://github.com/dkhamsing/open-source-ios-apps and edit contents.json again and add your entry

I am closing this pull

**Pull request closed without merging**
