### PR TITLE
Add Pocket-Code by @painhapp

### PR DESCRIPTION
**Pull request by painhapp**
1. [x] Project URL:
2. [x] Update contents.json instead of README 
3. [x] One project per pull request
4. [x] Screenshot included 
5. [x] Avoid iOS or open-source in description as it is assumed
6. [x] Use this commit title format if applicable: Add app-name by @github-username
7. [x] Use approved format for your entry

### CODE REVIEW

**Comment by painhapp** [comment]
I copied the promo text of the app as description. Should I remove ", directly on your phone or tablet" as it is redundant?

**Comment by painhapp** [comment]
@Screenshots: Not included as they will soon be changed.

**Comment by dkhamsing** [comment]
Description is ok

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vpeschenkov** [comment]
@painhapp  thank you!

**Pull request merged**
