### PR TITLE
Add ReviewMonitor by @RishabhTayal

### PR DESCRIPTION
**Pull request by RishabhTayal**
1. [x] Project URL: https://github.com/RishabhTayal/ReviewMonitor
2. [x] Update contents.json instead of README 
3. [x] One project per pull request
4. [x] Avoid iOS or open-source in description as it is assumed
5. [x] Use this commit title format if applicable: Add app-name by @github-username
6. [x] Use approved format for your entry

### CODE REVIEW

**Comment by dkhamsing** [comment]
Thank you!

**Comment by vpeschenkov** [comment]
@RishabhTayal Hi! To show `swift` instead of `objc`, you should add the next `"tags": [ "swift" ]` in `contents.json` for your app. Also, for more information you can read [this](https://github.com/dkhamsing/open-source-ios-apps/blob/master/.github/CONTRIBUTING.md).

**Comment by dkhamsing** [comment]
Yup sorry about this - feel free to open a pull request, or I will fix it later

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dkhamsing** [comment]
Fixed

**Comment by RishabhTayal** [comment]
@dkhamsing Thanks. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
