### PR TITLE
Switch to JSON Format

### PR DESCRIPTION
**Pull request by scribblemaniac**
There are a few things that still need to be done to fully use this:
- [ ] Update contributing guidelines
- [ ] Create a generator script to go from JSON to Markdown
- [ ] Update ci scripts to validate json, and even better yet check for missing attributes, invalid category references, etc.

For more information see #267 

---

- [x] review json format

### CODE REVIEW

**Comment by dkhamsing** [comment]
Thanks for your work, will review asap

**Comment by dkhamsing** [comment]
@kvnbautista please do not add any projects to repo while we evaluate switching format (all data would be in json)

thanks

**Comment by kvnbautista** [comment]
okay no problem

**Comment by dkhamsing** [comment]
Big thank you, this was great work 🎉

**Comment by dkhamsing** [comment]
Will follow up for generating the readme and updating contribution etc

**Comment by scribblemaniac** [comment]
No problem, glad I could help.

**Comment by dkhamsing** [comment]
@scribblemaniac are you interested in helping to maintain this repo? if you are leave me your email 😉

**Comment by scribblemaniac** [comment]
@dkhamsing I would be interested in that. You can contact me at thescribblemaniac@gmail.com

**Comment by dkhamsing** [comment]
@scribblemaniac will add you after 275 is merged, thanks!

**Comment by dkhamsing** [comment]
@scribblemaniac you've been added!

**Comment by scribblemaniac** [comment]
@dkhamsing Thanks!

**Pull request merged**
