### PR TITLE
Add Argent by @sinanku

### PR DESCRIPTION
**Pull request by sinanku**
1. [x] Project URL: https://github.com/argent-os/argent-ios
2. [x] Update contents.json instead of README 
3. [x] One project per pull request
4. [x] Avoid iOS or open-source in description as it is assumed
5. [x] Use this commit title format if applicable: Add app-name by @github-username
6. [x] Use approved format for your entry

--- 

*edited*

### CODE REVIEW

**Comment by dkhamsing** [comment]
@sinanku thanks for the contribution!

the README is pretty light on details
what does the app do? is this on the app store?

**Comment by sinanku** [comment]
@dkhamsing thanks! It's an app I wrote a year ago to handle mobile payments (one-time, recurring, bitcoin).  It used to be on the App Store until I took it down. Since I made it by myself I didn't keep the README updated, but am planning on writing a guide soon on how to get it up and running.

**Comment by dkhamsing** [comment]
ah i see
so is this a project we can use now, or maybe we should have this in the archive.. ?

**Comment by sinanku** [comment]
Original upload of the second release version.

screen shot 2017-07-21 at 12 11 28 pm

The project would require config keys for Plaid and Stripe in production, but it should be able to be run locally without them.  I would say if the API and app are downloaded and run at the same time locally it should be able to run as long as a MongoDB instance is running on the machine locally.  Quite a few nice UI features that people might find useful in production apps down the road.

If someone wanted to release their own version it could be done in about a week without the Plaid configuration, since Stripe is relatively easy to get keys from.

**Comment by sinanku** [comment]
I will continue to maintain the main branch if anyone wishes to make contributions, and be the active maintainer of the repository.

**Comment by dkhamsing** [comment]
yeah it's not just an ios app, a whole service :)

thx!

**Pull request merged**
