### PR TITLE
Added iOS 8 sampler

### PR DESCRIPTION
**Pull request by sanketfirodiya**
Awesome app that showcases the new features in iOS 8

### CODE REVIEW

**Comment by dkhamsing** [comment]
Thanks for the link, again.. would like to link to apps only (not list)

**Comment by sanketfirodiya** [comment]
@dkhamsing please take a look again, it looks like a list but is an app actually :)

**Comment by dkhamsing** [comment]
hi, thanks for your contribution

you added 2 items
- sample-watchKit-apps: this is a list of app/resources
- iOS 8 Samplers: this was added here c5cbb9c

**Comment by sanketfirodiya** [comment]
cool, thanks!

**Pull request closed without merging**
