### PR TITLE
Added JSON schema support to CI

### PR DESCRIPTION
**Pull request by scribblemaniac**
See #276 for details.

### CODE REVIEW

**Comment by dkhamsing** [comment]
Conflicts.. 😅

**Comment by scribblemaniac** [comment]
> Conflicts.. 😅

Figures 😀

**Comment by scribblemaniac** [comment]
Oh, and I just noticed, I didn't change data.json to content.json in this pull. The circle.yml will have to be updated accordingly as well.

**Comment by dkhamsing** [comment]
I'll apply your changes, thanks

**Pull request closed without merging**
