### PR TITLE
Add Compass by @zntfdr

### PR DESCRIPTION
**Pull request by zntfdr**
1. [X] Project URL: https://github.com/zntfdr/Compass/
2. [X] Update contents.json instead of README 
3. [X] One project per pull request
4. [X] Avoid iOS or open-source in description as it is assumed
5. [X] Use this commit title format if applicable: Add app-name by @github-username
6. [X] Use approved format for your entry

### CODE REVIEW

**Comment by dkhamsing** [comment]
thx!
will be making some slight modifications :)

**Comment by zntfdr** [comment]
Great! Hope I didn't do anything wrong 😅

**Comment by dkhamsing** [comment]
No biggie, if you're curious: 70bafa6

**Comment by zntfdr** [comment]
Ha! ok 😁

Thanks!

Federico Zanetello (Twitter <https://twitter.com/zntfdr>)

Kimchi Media <http://kimchi.media> - Your City Transportation Map
(
Twitter <https://twitter.com/kimchi_media>)
Bangkok <http://kimchi.media/metro/bangkok/en/>, Chengdu
<http://kimchi.media/metro/chengdu/en/>, Chongqing
<http://kimchi.media/metro/chongqing/en/>, Kuala Lumpur
<http://kimchi.media/metro/kuala_lumpur/en/>, Nanjing
<http://kimchi.media/metro/nanjing/en/>, Osaka
<http://kimchi.media/metro/osaka/en/>, Tianjin
<http://kimchi.media/metro/tianjin/en/>

**Pull request merged**
