### PR TITLE
Add Closebox by @peteog

### PR DESCRIPTION
**Pull request by peteog**
0. [x] Project URL: https://github.com/peteog/Closebox
1. [x] Update contents.json instead of README 
2. [x] One project per pull request
3. [x] Project added at the end of the list (a script sorts projects automatically)
4. [x] Avoid iOS or open-source in description as it is assumed
5. [x] Use this commit title format if applicable: Add app-name by @github-username
6. [x] Use approved format for your entry

### CODE REVIEW

**Comment by dkhamsing** [comment]
@peteog looking good Pete
We have to fix some validation on our end but your entry will be merged

**Comment by dkhamsing** [comment]
@scribblemaniac hey buddy
can you update the schema to allow this type of values for itunes

https://itunes.apple.com/gb/app/closebox-find-closest-postbox/id556364813

is this issue the /gb ? anyway, that is allowed

**Comment by peteog** [comment]
ah, it's an interesting one in this case as the app is only available in the UK store

**Comment by dkhamsing** [comment]
@peteog yeah no worries, we should support that

**Comment by dkhamsing** [comment]
In fact it is ok to merge, the readme generation will just get stuck

**Comment by dkhamsing** [comment]
Thx!

**Comment by dkhamsing** [comment]
Issue tracking #298

**Comment by dkhamsing** [comment]
@peteog Added https://github.com/dkhamsing/open-source-ios-apps/commit/c92bed89c6707b5f74dd96790b1c3bf8a931ef41

**Comment by dkhamsing** [comment]
?? bffb159d12da205b1cffbfe7903b35685f3486cf

**Pull request merged**
