### PR TITLE
Add CalendarApp by richardtop

### PR DESCRIPTION
**Pull request by richardtop**
1. [x] Project URL:
2. [x] Update contents.json instead of README 
3. [x] One project per pull request
4. [x] Screenshot included 
5. [x] Avoid iOS or open-source in description as it is assumed
6. [x] Use this commit title format if applicable: Add app-name by @github-username
7. [x] Use approved format for your entry

### CODE REVIEW

**Comment by dkhamsing** [comment]
Thx @richardtop! Could we edit the entry in #916 instead?

**Comment by richardtop** [comment]
Hi, that one could be replaced, of course. But in fact, those two are different apps:
1. The first one (CalendarKit example) is just a sample app with generated data
2. The second one (CalendarApp) is actual calendar working with the user's EventKit calendar, thus requiring the events to be created beforehand.

**Comment by dkhamsing** [comment]
@richardtop 
Seems this one is much more interesting, I will add it and remove the other one. Thank you!

**Comment by richardtop** [comment]
Sounds good! Thanks!

**Pull request merged**
