### PR TITLE
Add scholars-of-wwdc by @michieriffic

### PR DESCRIPTION
**Pull request by michieriffic**
0. [x] Project URL:
1. [x] Update contents.json instead of README 
2. [x] One project per pull request
3. [x] Project added at the end of the list (a script sorts projects automatically)
4. [x] Avoid iOS or open-source in description as it is assumed
5. [x] Use this commit title format if applicable: Add app-name by @github-username
6. [x] Use approved format for your entry

### CODE REVIEW

**Comment by dkhamsing** [comment]
1. can you rebase/fix the conflicts?
2. also the license should be lowercase `mit`

thanks!

**Comment by michieriffic** [comment]
@dkhamsing I cannot find where the conflict is. But circleci, is saying there is a conflict?

**Comment by dkhamsing** [comment]
well the conflict is between your fork and this repo

**Comment by dkhamsing** [comment]
ci is complaining about the itunes link.. can you replace by this instead

https://itunes.apple.com/app/scholars-of-wwdc/id999731893

**Comment by dkhamsing** [comment]
thx!

**Comment by dkhamsing** [comment]
you're close! do you know how to rebase ? 
https://help.github.com/articles/resolving-merge-conflicts-after-a-git-rebase/

**Comment by michieriffic** [comment]
Hi @dkhamsing sorry just got back. I was able to rebase it and fix conflict on my fork. Do I need to create a new pull request for this? :)

**Comment by dkhamsing** [comment]
after you fix the conflict, you can push to the same fork

**Comment by michieriffic** [comment]
@dkhamsing I have fixed the conflicts already. But the pull request here isn't updating [michieriffic/open-source-ios-apps](https://github.com/michieriffic/open-source-ios-apps)

Can you check my fork if I have missed anything? thx

**Comment by dkhamsing** [comment]
hey just took a look
this is the fork you want to update https://github.com/michieriffic/open-source-ios-apps/tree/patch-1

**Comment by michieriffic** [comment]
oh. got it. wait :)

**Comment by michieriffic** [comment]
@dkhamsing got another check failed. - 

Issues :-(
> Links 
  1. [L17]  http://zbar.sourceforge.net/ Connection reset by peer 
  2. [L37]  http://projectm.sourceforge.net/ Connection reset by peer

**Comment by dkhamsing** [comment]
dont worry about those, thanks!!

**Comment by michieriffic** [comment]
@dkhamsing I noticed that the changes were already committed to Master but the app isn't listed on the Readme file. :)

**Comment by dkhamsing** [comment]
should be listed soon, thanks

**Pull request merged**
