### PR TITLE
Update contents.json

### PR DESCRIPTION
**Pull request by dl-alexandre**
Replaced SF Symbol App with more updated app

Thank you!

### CODE REVIEW

**Comment by dkhamsing** [comment]
This is a different app??

**Comment by dl-alexandre** [comment]
Correct. There haven't been updates to the other app for multiple years which is a significant camping of SF Symbols

**Comment by dkhamsing** [comment]
Ok pls close this and create a new pull request to add the new app instead of replacing the old one 

Thx

**Comment by dkhamsing** [comment]
I will add this myself, thank you!

**Pull request closed without merging**
