### PR TITLE
Add DropColour by @elpassion

### PR DESCRIPTION
**Pull request by mateuszszklarek**
0. [x] Project URL: https://github.com/elpassion/DropColour-iOS
1. [x] Update contents.json instead of README 
2. [x] One project per pull request
3. [x] Project added at the end of the list (a script sorts projects automatically)
4. [x] Avoid iOS or open-source in description as it is assumed
5. [x] Use this commit title format if applicable: Add app-name by @github-username
6. [x] Use approved format for your entry

### CODE REVIEW

**Comment by mateuszszklarek** [comment]
@dkhamsing Can you check my PR?

**Comment by dkhamsing** [comment]
yes i will, thanks for your pull request

**Comment by dkhamsing** [comment]
1. can you rebase/fix the conflicts?
2. also the license should be lowercase `mit`

thanks!

**Comment by dkhamsing** [comment]
looks like the itunes link has some validation issues, can you update with this instead

https://itunes.apple.com/app/dropcolour/id1046339763

**Comment by dkhamsing** [comment]
wow buddy the diff is a mess 😉

**Pull request closed without merging**
