### PR TITLE
New Repo Structure

### LINKED ISSUE #267: Consistent Format
Right now there are two listing formats
- apps on app store
- apps not on app store

The list should be consistent and follow the format of apps on app store (link listed below, indented)

---

Before:

- [app not on app store](link): description

After:

- app not on app store: description
  - http://app-link.co

### PR DESCRIPTION
**Pull request by dkhamsing**
The data now resides in `contents.json`, updating it generates the README.

Continued from #273
Includes #277 
Closes #267

- [x] merge changes in 277
- [x] generate README 
- [x] ~~rename `lang`, use country codes (jp for japan, es for spain etc)~~
- [x] fix ci: delete duplicate items and update `category` value to list 
- [x] update convert script to grab apps from multiple categories 
- [x] update CONTRIBUTING.md
- [x] add comment header with contributing instructions
- [ ] update ci to trigger conversion and pushing to master: deploy.sh
- [ ] merge open pulls  

---

- [x] unrelated but add .md to pull_request_template

### CODE REVIEW

**Comment by scribblemaniac** [comment]
> rename lang, use country codes (jp for japan, es for spain etc)

Is this really a good idea? This idea occurred to me as well when building the converter, because some information will inevitably be lost if we use languages. For example on one of them, Brazilian becomes Portuguese. But for example, just pick a random english project and ask, "What country is that from?" Likely you won't be able to tell, it could be UK, US, Canada, Australia, Guyana, etc. Even for one in Chinese, how can you distinguish that from someone who just likes to show off their Google Translate skills? I came to the conclusion that a country code feels misleading. What are your thoughts on this?

**Comment by dkhamsing** [comment]
@scribblemaniac oh I see what you mean.. then we can leave it alone for now. thanks!

**Comment by dkhamsing** [comment]
@scribblemaniac however the country seems to be relevant for a location / local app.. what do you think?

**Comment by scribblemaniac** [comment]
I guess both then 😜 

`lang` will indicate the primary language of the project, and maybe a new `country` attribute where the location is known. A string value with [ISO 3166-1 alpha-2 codes](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) perhaps?

**Comment by dkhamsing** [comment]
Dunno if that's overkill
We can hold off for now

**Comment by dkhamsing** [comment]
@kvnbautista there is now a new process for adding apps to this repo, it will be done through updating **contents.json** instead

More info https://github.com/dkhamsing/open-source-ios-apps/blob/master/.github/CONTRIBUTING.md

**Comment by dkhamsing** [comment]
@scribblemaniac updated schema.json: `description` while preferred is not required

**Comment by scribblemaniac** [comment]
@dkhamsing got it thanks

**Comment by dkhamsing** [comment]
GIF on adding an entry

add-entry

**Pull request merged**
